import {
  User,
  WorkerProfile,
  ServiceItem,
  Booking,
  WageLedgerEntry,
  WorkerAppeal,
  CollectiveBargaining,
  Testimonial,
  DemandLocation
} from '@/types';

export const DEMO_USERS: Record<string, User> = {
  worker: {
    id: 'usr-worker-01',
    email: 'sunita.sharma@sahayakseva.org',
    phone: '+91 98765 43210',
    fullName: 'Sunita Sharma',
    role: 'worker',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    city: 'New Delhi',
    address: 'B-42, Malviya Nagar, New Delhi',
    verifiedEmail: true,
    verifiedPhone: true,
    cooperativeBranch: 'South Delhi Skilled Electricians Guild (Coop #104)',
    createdAt: '2023-04-15',
  },
  customer: {
    id: 'usr-cust-02',
    email: 'rahul.verma@gmail.com',
    phone: '+91 98111 22334',
    fullName: 'Rahul Verma',
    role: 'customer',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    city: 'New Delhi',
    address: '14, Golf Links, New Delhi',
    verifiedEmail: true,
    verifiedPhone: true,
    createdAt: '2023-08-10',
  },
  admin: {
    id: 'usr-admin-03',
    email: 'priya.patel@sahayakseva.org',
    phone: '+91 98222 99887',
    fullName: 'Priya Patel',
    role: 'admin',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400',
    city: 'New Delhi',
    address: 'Federation Secretariat, Connaught Place, New Delhi',
    verifiedEmail: true,
    verifiedPhone: true,
    cooperativeBranch: 'National Federation of Gig & Platform Cooperatives',
    createdAt: '2022-11-01',
  },
  business: {
    id: 'usr-biz-04',
    email: 'facilities@bluepeak.in',
    phone: '+91 98333 44556',
    fullName: 'Amit Sen (Facilities Director)',
    role: 'business',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    city: 'Gurugram',
    address: 'Cyber City, Tower B, Gurugram',
    verifiedEmail: true,
    verifiedPhone: true,
    createdAt: '2024-01-20',
  }
};

export const SERVICES_DATA: ServiceItem[] = [
  {
    id: 'srv-cleaning',
    title: 'Eco Deep Home Cleaning',
    slug: 'eco-deep-home-cleaning',
    category: 'Cleaning',
    shortDescription: 'Hospital-grade eco-friendly home sanitization by worker-owned hygiene teams.',
    fullDescription: 'Comprehensive top-to-bottom residential cleaning using non-toxic certified products. Includes kitchen degreasing, bathroom descaling, balcony wash, and mattress UV vacuuming. Handled by a 3-member cooperative cleaning team with complete worker insurance.',
    basePrice: 1899,
    priceUnit: 'per 2BHK flat',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=800',
    colorCode: 'coop-green',
    badgeText: 'Most Booked',
    popular: true,
    includedFeatures: [
      '3-member verified cooperative crew',
      'Child & pet safe certified organic detergents',
      'High-pressure steam disinfections',
      'Free 48-hour satisfaction re-clean guarantee',
      '100% transparent wage distribution'
    ],
    certifiedWorkersCount: 420,
  },
  {
    id: 'srv-electrical',
    title: 'Certified Electrical & Smart Living',
    slug: 'certified-electrical-repairs',
    category: 'Repairs',
    shortDescription: 'Licensed electrician guild members for surge protection, wiring & switchgear.',
    fullDescription: 'Government-certified Master Electricians for power trip debugging, heavy appliance wiring (AC/Geyser/EV Chargers), distribution board overhaul, and smart inverter setups. All work backed by a 60-day cooperative guild workmanship warranty.',
    basePrice: 550,
    priceUnit: 'per hour',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=800',
    colorCode: 'card-purple',
    badgeText: 'Guild Certified',
    popular: true,
    includedFeatures: [
      'Certified Class-A wireman license holders',
      'Digital insulation resistance testing',
      'Pre-negotiated fair union rates (₹550/hr)',
      'Accident & surge liability insurance covered',
      'Parts sourced at wholesale cooperative discount'
    ],
    certifiedWorkersCount: 310,
  },
  {
    id: 'srv-plumbing',
    title: 'Master Plumbing & Sanitation',
    slug: 'master-plumbing-repairs',
    category: 'Repairs',
    shortDescription: 'Leak detection, pressure pump tuning, pipeline descaling, and sanitary fitting.',
    fullDescription: 'Reliable plumbing solutions provided by experienced municipal plumbing guild members. Specializing in concealed seepage detection, booster pump installation, sanitaryware fitment, and non-invasive pipeline unclogging.',
    basePrice: 499,
    priceUnit: 'per visit + parts',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=800',
    colorCode: 'card-blue',
    badgeText: 'Quick Dispatch',
    popular: false,
    includedFeatures: [
      'Thermal imaging leak detection',
      'Sanitary grade seals and CPVC pipe repair',
      '90-day anti-seepage cooperative warranty',
      'Digital invoice with zero hidden markups'
    ],
    certifiedWorkersCount: 280,
  },
  {
    id: 'srv-healthcare',
    title: 'Senior & Post-Op Compassionate Care',
    slug: 'senior-and-post-op-care',
    category: 'Healthcare',
    shortDescription: 'Trained geriatric care assistants, vital monitoring, and patient mobility aid.',
    fullDescription: 'Verified home nursing and bedside attendant services by our Women-Led Healthcare Cooperative. Services include bedridden elder care, vital monitoring, medication prompts, light physiotherapy mobility exercises, and meal support.',
    basePrice: 1200,
    priceUnit: 'per 8-hour shift',
    image: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&q=80&w=800',
    colorCode: 'soft-teal',
    badgeText: 'Women-Led Coop',
    popular: true,
    includedFeatures: [
      'BLS (Basic Life Support) certified attendants',
      'Daily vitals & medication log sent to family',
      'Emergency SOS auto-link to local hospital',
      'Compassionate background-checked caregivers'
    ],
    certifiedWorkersCount: 195,
  },
  {
    id: 'srv-carpentry',
    title: 'Heritage Carpentry & Furniture Restoration',
    slug: 'heritage-carpentry-restoration',
    category: 'Custom',
    shortDescription: 'Master woodworkers preserving traditional joinery, polishing, and custom cabinetry.',
    fullDescription: 'Experienced artisan carpenters specializing in solid teak/sheesham restoration, bespoke shelving, kitchen cabinet hinges, and antique French polishing. Honoring traditional craftsmanship with fair wages.',
    basePrice: 650,
    priceUnit: 'per hour',
    image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&q=80&w=800',
    colorCode: 'warning',
    badgeText: 'Heritage Craft',
    popular: false,
    includedFeatures: [
      'Authentic seasoned timber knowledge',
      'Precision concealed hinge adjustments',
      'Natural linseed oil and melamine polish',
      'Preserves generational artisan skills'
    ],
    certifiedWorkersCount: 140,
  },
  {
    id: 'srv-events',
    title: 'Community Events Logistics & Catering Crew',
    slug: 'community-events-logistics',
    category: 'Events',
    shortDescription: 'Trained hospitality crews, stage setup, buffet management, and post-event cleanup.',
    fullDescription: 'Scalable teams of cooperative event workers for family weddings, corporate gatherings, and community festivals. Punctual, respectful, and coordinated under an on-site cooperative team lead.',
    basePrice: 3500,
    priceUnit: 'per 4-member crew / 6 hrs',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=800',
    colorCode: 'card-purple',
    badgeText: 'Team Booking',
    popular: false,
    includedFeatures: [
      'Uniformed hospitality & service attendants',
      'Dedicated on-site crew coordinator',
      'Zero-waste food distribution to charities',
      'No middleman agency commissions'
    ],
    certifiedWorkersCount: 220,
  },
  {
    id: 'srv-painting',
    title: 'Eco Architectural Painting & Waterproofing',
    slug: 'eco-architectural-painting',
    category: 'Repairs',
    shortDescription: 'Low-VOC airless spray painting, terrace waterproofing, and moisture remediation.',
    fullDescription: 'Professional painters cooperative using dust-free mechanized sanders and non-toxic paints. Guaranteed uniform finish with comprehensive wall dampness diagnosis and primer sealing.',
    basePrice: 12,
    priceUnit: 'per sq. ft.',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=800',
    colorCode: 'coop-green',
    badgeText: '3-Yr Warranty',
    popular: false,
    includedFeatures: [
      'Laser area measurement with transparent quotation',
      'Floor & furniture masking protection included',
      'Zero volatile chemical (Low-VOC) paints',
      'Moisture meter diagnostic report'
    ],
    certifiedWorkersCount: 175,
  },
  {
    id: 'srv-appliance',
    title: 'Appliance Diagnostics & HVAC Servicing',
    slug: 'appliance-diagnostics-servicing',
    category: 'Repairs',
    shortDescription: 'AC jet cleaning, refrigerator gas charging, and washing machine drum repair.',
    fullDescription: 'High-precision diagnostics for inverter ACs, front-load washing machines, and microwave ovens. Spare parts supplied at direct manufacturer wholesale rates without inflated retail margins.',
    basePrice: 449,
    priceUnit: 'per service call',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=800',
    colorCode: 'card-blue',
    badgeText: '90-Day Guarantee',
    popular: true,
    includedFeatures: [
      'High-pressure water jacket AC cleaning',
      'Digital refrigerant pressure testing',
      'Genuine OEM spare parts with barcode audit',
      'Worker receives 80% direct net wage'
    ],
    certifiedWorkersCount: 290,
  }
];

export const WORKERS_DATA: WorkerProfile[] = [
  {
    id: 'wrk-01',
    userId: 'usr-worker-01',
    fullName: 'Sunita Sharma',
    trade: 'Master Electrician',
    experienceLevel: '5+yr',
    skills: ['Three-Phase Wiring', 'Distribution Boards', 'Solar Inverter Sync', 'Surge Arrester Installation'],
    certifications: ['National Skill Development Corp (NSDC) Level 5', 'Govt Electrical Supervisor License'],
    rating: 4.94,
    totalJobsCompleted: 348,
    verifiedStatus: 3,
    communityVouchesCount: 142,
    minRate: 550,
    avgHourlyRate: 580,
    womenWorker: true,
    backgroundCheckStatus: 'verified',
    insuranceEnrolled: true,
    profilePhotoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    bio: 'Pioneering member of South Delhi Skilled Electricians Cooperative. Over 8 years of high-voltage industrial & residential electrical troubleshooting. Passionate about empowering women in technical trades.',
    available: true,
    location: 'South Delhi & NCR',
  },
  {
    id: 'wrk-02',
    userId: 'usr-worker-02',
    fullName: 'Rajesh Kumar M.',
    trade: 'Senior Sanitary & Plumbing Engineer',
    experienceLevel: '5+yr',
    skills: ['Acoustic Seepage Detection', 'Booster Pumps', 'Hydro-Jet Pipeline Cleansing', 'Geberit Concealed Cisterns'],
    certifications: ['Indian Plumbing Association Master Certified', 'NSDC Sanitation Specialist'],
    rating: 4.88,
    totalJobsCompleted: 412,
    verifiedStatus: 3,
    communityVouchesCount: 189,
    minRate: 499,
    avgHourlyRate: 520,
    womenWorker: false,
    backgroundCheckStatus: 'verified',
    insuranceEnrolled: true,
    profilePhotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    bio: 'Lead coordinator at Central Delhi Plumbing Cooperative. Believes in precision work, transparent billing, and zero repeat leaks. Mentored 24 apprentice plumbers.',
    available: true,
    location: 'Central & West Delhi',
  },
  {
    id: 'wrk-03',
    userId: 'usr-worker-03',
    fullName: 'Ananya Deshmukh',
    trade: 'Senior Healthcare Caregiver & Nurse',
    experienceLevel: '3-5yr',
    skills: ['Post-Stroke Rehabilitation', 'Vital Tracking', 'Dementia Support', 'Subcutaneous Injection'],
    certifications: ['Registered Nurse (B.Sc Nursing)', 'Certified BLS & First Aid Provider'],
    rating: 4.97,
    totalJobsCompleted: 219,
    verifiedStatus: 3,
    communityVouchesCount: 164,
    minRate: 1200,
    avgHourlyRate: 1250,
    womenWorker: true,
    backgroundCheckStatus: 'verified',
    insuranceEnrolled: true,
    profilePhotoUrl: 'https://images.unsplash.com/photo-1594824813579-05244e825a07?auto=format&fit=crop&q=80&w=400',
    bio: 'Former ICU nurse dedicated to compassionate in-home geriatric assistance. Core committee member of the Delhi Women Caregivers Cooperative. Prioritizes dignity and patient comfort.',
    available: true,
    location: 'South Delhi & Noida',
  },
  {
    id: 'wrk-04',
    userId: 'usr-worker-04',
    fullName: 'Mohammad Farooq',
    trade: 'Master Wood Craftsman',
    experienceLevel: '5+yr',
    skills: ['Hand-Carved Joinery', 'Antique Teak Restoration', 'Polyurethane High-Gloss Finishing', 'Acoustic Wall Paneling'],
    certifications: ['National Heritage Artisan Awardee', 'Guild Master Craftsman Tier 1'],
    rating: 4.91,
    totalJobsCompleted: 184,
    verifiedStatus: 2,
    communityVouchesCount: 98,
    minRate: 650,
    avgHourlyRate: 700,
    womenWorker: false,
    backgroundCheckStatus: 'verified',
    insuranceEnrolled: true,
    profilePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    bio: 'Third-generation wood artisan from Old Delhi. Preserving traditional Indian joinery techniques while adopting modern German precision hardware for contemporary homes.',
    available: false,
    location: 'Old Delhi, North Delhi & Ghaziabad',
  },
  {
    id: 'wrk-05',
    userId: 'usr-worker-05',
    fullName: 'Pooja Rani',
    trade: 'Hygiene & Deep Cleaning Specialist',
    experienceLevel: '3-5yr',
    skills: ['Eco Degreasing', 'Upholstery Extraction', 'Marble Crystallization', 'Kitchen Mold Eradication'],
    certifications: ['Certified Green Cleaning Associate', 'Safety & PPE Compliance Tier 3'],
    rating: 4.89,
    totalJobsCompleted: 295,
    verifiedStatus: 3,
    communityVouchesCount: 115,
    minRate: 450,
    avgHourlyRate: 480,
    womenWorker: true,
    backgroundCheckStatus: 'verified',
    insuranceEnrolled: true,
    profilePhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    bio: 'Founder-member of Pragati Sanitation Workers Collective. We take pride in revitalizing living spaces using health-safe, eco-friendly enzymatic cleaning technology.',
    available: true,
    location: 'Gurugram & South Delhi',
  },
  {
    id: 'wrk-06',
    userId: 'usr-worker-06',
    fullName: 'Virendra Singh',
    trade: 'HVAC & Refrigeration Technician',
    experienceLevel: '5+yr',
    skills: ['Inverter PCB Micro-soldering', 'R32 Gas Recovery', 'Chiller Coil Repair', 'Ductless Mini-Split Tuning'],
    certifications: ['EPA Section 608 Universal Refrigeration', 'Daikin Certified Field Specialist'],
    rating: 4.86,
    totalJobsCompleted: 380,
    verifiedStatus: 3,
    communityVouchesCount: 130,
    minRate: 449,
    avgHourlyRate: 500,
    womenWorker: false,
    backgroundCheckStatus: 'verified',
    insuranceEnrolled: true,
    profilePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    bio: '12 years troubleshooting climate systems across residential and commercial buildings. Fair, upfront quotations with warranty-backed genuine spares.',
    available: true,
    location: 'East Delhi & Noida',
  }
];

export const BOOKINGS_DATA: Booking[] = [
  {
    id: 'bkg-101',
    customerId: 'usr-cust-02',
    customerName: 'Rahul Verma',
    customerPhone: '+91 98111 22334',
    workerId: 'wrk-01',
    workerName: 'Sunita Sharma',
    workerPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    workerTrade: 'Master Electrician',
    serviceTitle: 'Certified Electrical & Smart Living',
    serviceCategory: 'Repairs',
    status: 'completed',
    scheduledDate: '2026-09-08',
    scheduledTime: '10:30 AM',
    durationHours: 3,
    location: '14, Golf Links, New Delhi',
    price: 1650,
    ratingGiven: 5,
    reviewComment: 'Outstanding professionalism. Sunita resolved an elusive tripping circuit that two other contractors failed to diagnose. Cooperative pricing was clear and transparent!',
    createdAt: '2026-09-07',
  },
  {
    id: 'bkg-102',
    customerId: 'usr-cust-02',
    customerName: 'Rahul Verma',
    customerPhone: '+91 98111 22334',
    workerId: 'wrk-05',
    workerName: 'Pooja Rani',
    workerPhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    workerTrade: 'Hygiene & Deep Cleaning Specialist',
    serviceTitle: 'Eco Deep Home Cleaning',
    serviceCategory: 'Cleaning',
    status: 'accepted',
    scheduledDate: '2026-09-14',
    scheduledTime: '09:00 AM',
    durationHours: 5,
    location: '14, Golf Links, New Delhi',
    price: 2400,
    createdAt: '2026-09-11',
  },
  {
    id: 'bkg-103',
    customerId: 'usr-cust-03',
    customerName: 'Meenakshi Iyer',
    customerPhone: '+91 98990 11223',
    workerId: 'wrk-01',
    workerName: 'Sunita Sharma',
    workerPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    workerTrade: 'Master Electrician',
    serviceTitle: 'Solar Inverter Sync & Load Balancing',
    serviceCategory: 'Repairs',
    status: 'pending',
    scheduledDate: '2026-09-15',
    scheduledTime: '02:00 PM',
    durationHours: 4,
    location: 'C-7, Hauz Khas Enclave, New Delhi',
    price: 2200,
    createdAt: '2026-09-12',
  },
  {
    id: 'bkg-104',
    customerId: 'usr-cust-04',
    customerName: 'Dr. Alok Nath',
    customerPhone: '+91 98450 67890',
    workerId: 'wrk-03',
    workerName: 'Ananya Deshmukh',
    workerPhoto: 'https://images.unsplash.com/photo-1594824813579-05244e825a07?auto=format&fit=crop&q=80&w=400',
    workerTrade: 'Senior Healthcare Caregiver & Nurse',
    serviceTitle: 'Senior & Post-Op Compassionate Care',
    serviceCategory: 'Healthcare',
    status: 'in-progress',
    scheduledDate: '2026-09-12',
    scheduledTime: '08:00 AM',
    durationHours: 8,
    location: 'Tower 4, DLF Phase 5, Gurugram',
    price: 1250,
    createdAt: '2026-09-10',
  },
  {
    id: 'bkg-105',
    customerId: 'usr-cust-05',
    customerName: 'Sanjay Malhotra',
    customerPhone: '+91 98100 44556',
    workerId: 'wrk-02',
    workerName: 'Rajesh Kumar M.',
    workerPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    workerTrade: 'Senior Sanitary Engineer',
    serviceTitle: 'Concealed Seepage Detection & Fix',
    serviceCategory: 'Repairs',
    status: 'completed',
    scheduledDate: '2026-09-04',
    scheduledTime: '11:00 AM',
    durationHours: 3,
    location: 'Sector 15, Noida',
    price: 1850,
    ratingGiven: 5,
    reviewComment: 'Rajesh used an ultrasonic detector and located the cracked joint without hacking up our entire bathroom wall. Saved us thousands!',
    createdAt: '2026-09-03',
  }
];

export const WAGE_LEDGER_DATA: WageLedgerEntry[] = [
  {
    id: 'wld-891',
    bookingId: 'bkg-101',
    workerId: 'wrk-01',
    serviceTitle: 'Certified Electrical DB Overhaul',
    customerName: 'Rahul Verma',
    date: '2026-09-08',
    grossAmount: 1650,
    workerNet: 1320,        // 80%
    insuranceDeduction: 82.5, // 5%
    coopOverhead: 165,       // 10%
    platformProfit: 82.5,    // 5%
    paymentStatus: 'completed',
  },
  {
    id: 'wld-890',
    bookingId: 'bkg-098',
    workerId: 'wrk-01',
    serviceTitle: 'Heavy Inverter Line Rewiring',
    customerName: 'Anil Kapoor',
    date: '2026-09-06',
    grossAmount: 3200,
    workerNet: 2560,        // 80%
    insuranceDeduction: 160, // 5%
    coopOverhead: 320,       // 10%
    platformProfit: 160,    // 5%
    paymentStatus: 'completed',
  },
  {
    id: 'wld-889',
    bookingId: 'bkg-094',
    workerId: 'wrk-01',
    serviceTitle: '3-Phase EV Charger Connection',
    customerName: 'Siddharth Roy',
    date: '2026-09-04',
    grossAmount: 2800,
    workerNet: 2240,        // 80%
    insuranceDeduction: 140, // 5%
    coopOverhead: 280,       // 10%
    platformProfit: 140,    // 5%
    paymentStatus: 'completed',
  },
  {
    id: 'wld-888',
    bookingId: 'bkg-091',
    workerId: 'wrk-01',
    serviceTitle: 'Emergency Short Circuit Diagnostics',
    customerName: 'Pooja Sethi',
    date: '2026-09-02',
    grossAmount: 1900,
    workerNet: 1520,        // 80%
    insuranceDeduction: 95,  // 5%
    coopOverhead: 190,       // 10%
    platformProfit: 95,     // 5%
    paymentStatus: 'completed',
  },
  {
    id: 'wld-887',
    bookingId: 'bkg-087',
    workerId: 'wrk-01',
    serviceTitle: 'Smart Home Automation Wiring',
    customerName: 'Vikram Joshi',
    date: '2026-08-30',
    grossAmount: 4500,
    workerNet: 3600,        // 80%
    insuranceDeduction: 225, // 5%
    coopOverhead: 450,       // 10%
    platformProfit: 225,    // 5%
    paymentStatus: 'completed',
  }
];

export const WORKER_MONTHLY_EARNINGS = [
  { day: 'Aug 15', earnings: 1450, jobs: 1 },
  { day: 'Aug 18', earnings: 2800, jobs: 2 },
  { day: 'Aug 21', earnings: 1900, jobs: 1 },
  { day: 'Aug 24', earnings: 3600, jobs: 2 },
  { day: 'Aug 27', earnings: 2200, jobs: 1 },
  { day: 'Aug 30', earnings: 4100, jobs: 3 },
  { day: 'Sep 02', earnings: 1900, jobs: 1 },
  { day: 'Sep 04', earnings: 2800, jobs: 2 },
  { day: 'Sep 06', earnings: 3200, jobs: 2 },
  { day: 'Sep 08', earnings: 1650, jobs: 1 },
  { day: 'Sep 10', earnings: 2900, jobs: 2 },
  { day: 'Sep 12', earnings: 3100, jobs: 2 },
];

export const WORKER_APPEALS_DATA: WorkerAppeal[] = [
  {
    id: 'app-501',
    workerId: 'wrk-01',
    workerName: 'Sunita Sharma',
    workerTrade: 'Master Electrician',
    workerPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    issueType: 'rating_invalidation',
    title: 'Customer retaliatory 1-star rating for refusing uncertified unsafe gas-line wiring',
    description: 'The client demanded that I connect an unauthorized 30A non-fused bypass next to an LPG pipeline in the basement. As per National Electric Code safety standards, I explained the fire risk and refused to do unsafe wiring. The client gave an angry 1-star rating. Requesting peer tribunal review to invalidate this vindictive rating.',
    filedDate: '2026-09-02',
    status: 'under_jury_review',
    juryVotes: {
      approve: 14, // 14 agreed to strike rating
      reject: 1,
      total: 15,
    },
    resolutionNote: 'Preliminary review indicates worker acted in 100% compliance with safety mandates. Final vote closes in 18 hours.',
  },
  {
    id: 'app-492',
    workerId: 'wrk-02',
    workerName: 'Rajesh Kumar M.',
    workerTrade: 'Senior Sanitary Engineer',
    workerPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    issueType: 'penalty_dispute',
    title: 'Automated late arrival fee during Delhi monsoon VIP route blockade',
    description: 'Platform algorithm auto-deducted ₹150 for 22-minute delay. The delay was caused by sudden security barricades on Shanti Path during international delegation movement. GPS movement logs and Delhi Traffic Police advisory attached as evidence.',
    filedDate: '2026-08-25',
    status: 'overturned',
    juryVotes: {
      approve: 15,
      reject: 0,
      total: 15,
    },
    resolutionNote: 'Penalty fully reversed. ₹150 refunded to Rajeshs cooperative wallet with apology.',
  }
];

export const COLLECTIVE_BARGAINING_DATA: CollectiveBargaining = {
  id: 'cb-elec-2026',
  trade: 'Electrical & Electronic Guild',
  currentMinRate: 550,
  proposedMinRate: 620,
  workersAgreed: 342,
  totalEligibleWorkers: 500,
  votingDaysRemaining: 2,
  status: 'active',
  rateHistory: [
    { month: 'Apr', rate: 480 },
    { month: 'May', rate: 500 },
    { month: 'Jun', rate: 510 },
    { month: 'Jul', rate: 530 },
    { month: 'Aug', rate: 540 },
    { month: 'Sep', rate: 550 },
  ],
};

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: 'tst-01',
    name: 'Sunita Sharma',
    role: 'Master Electrician & Coop Board Member',
    trade: 'Electrical Services',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    quote: 'On commercial gig platforms, 30% to 40% of my hard-earned money vanished into corporate commissions. With Sahayak Seva, 80% goes straight into my pocket, 5% covers accident health insurance, and 10% builds our cooperative capital. We own our future.',
    rating: 5,
    coopChapter: 'South Delhi Skilled Workers Guild',
  },
  {
    id: 'tst-02',
    name: 'Vikram & Radhika Mehta',
    role: 'Homeowners',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    quote: 'Knowing that the professionals who come to our home are treated with dignity and paid fair union wages completely changes the service quality. The cooperative workers are punctual, skilled, and take genuine pride in their craft.',
    rating: 5,
    coopChapter: 'Customer Member, Hauz Khas Chapter',
  },
  {
    id: 'tst-03',
    name: 'Mohammad Farooq',
    role: 'Artisan Woodworker',
    trade: 'Heritage Restoration',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    quote: 'The Heritage Skills Premium on Sahayak Seva protects generational woodwork from being treated like cheap modular furniture. When algorithms treated us like disposable cogs, Sahayak Seva gave us an appeal jury of our peers.',
    rating: 5,
    coopChapter: 'Walled City Craftsmen Society',
  }
];

export const DEMAND_LOCATIONS_DATA: DemandLocation[] = [
  { id: 'loc-01', zone: 'South Delhi (Malviya Nagar, Saket, GK)', city: 'Delhi', demandLevel: 'surge', activeWorkers: 184, openJobs: 42, avgHourlySurge: '+15% Coop Bonus' },
  { id: 'loc-02', zone: 'Gurugram Cyber City & Golf Course Rd', city: 'NCR', demandLevel: 'high', activeWorkers: 142, openJobs: 36, avgHourlySurge: '+10% Coop Bonus' },
  { id: 'loc-03', zone: 'Noida Expressway & Sector 62', city: 'NCR', demandLevel: 'high', activeWorkers: 120, openJobs: 28, avgHourlySurge: 'Standard' },
  { id: 'loc-04', zone: 'Central Delhi (CP, Patel Nagar, Karol Bagh)', city: 'Delhi', demandLevel: 'moderate', activeWorkers: 95, openJobs: 18, avgHourlySurge: 'Standard' },
  { id: 'loc-05', zone: 'Bengaluru (Koramangala, HSR, Indiranagar)', city: 'Bengaluru', demandLevel: 'surge', activeWorkers: 240, openJobs: 54, avgHourlySurge: '+20% Coop Bonus' },
];

export const US_PRESENTS_9 = [
  {
    id: 'usp-1',
    title: 'Collective Bargaining Dashboard',
    desc: 'Workers vote democratically on minimum hourly rates, surge caps, and guild policies in real-time.',
    icon: 'Users',
    badge: 'Democratic Voice',
  },
  {
    id: 'usp-2',
    title: 'Gender-First Safety Network',
    desc: 'Women workers can filter for verified women-only households, emergency SOS, and verified peer escorts.',
    icon: 'ShieldCheck',
    badge: 'Women-Led',
  },
  {
    id: 'usp-3',
    title: 'Wage Transparency Ledger',
    desc: 'Every single rupee is accounted for: 80% to worker, 5% insurance, 10% coop overhead, 5% platform operations.',
    icon: 'ReceiptText',
    badge: '100% Audited',
  },
  {
    id: 'usp-4',
    title: 'Neighborhood Batch Optimization',
    desc: 'Algorithms group nearby jobs to minimize travel fatigue and cut fuel pollution by over 40%.',
    icon: 'MapPin',
    badge: 'Eco Routing',
  },
  {
    id: 'usp-5',
    title: 'Multi-Service Bundling',
    desc: 'Book electricians, plumbers, and deep cleaners in synchronized teams without redundant call-out charges.',
    icon: 'Layers',
    badge: 'Coop Savings',
  },
  {
    id: 'usp-6',
    title: 'Worker Algorithmic Appeal System',
    desc: 'No unfair automated deactivations. Every dispute is arbitrated by a democratic peer jury of fellow workers.',
    icon: 'Scale',
    badge: 'Peer Justice',
  },
  {
    id: 'usp-7',
    title: 'Heritage Skills Premium',
    desc: 'Master artisans in generational crafts (stone, brass, hand-carved wood) receive specialized premium rates.',
    icon: 'Sparkles',
    badge: 'Cultural Equity',
  },
  {
    id: 'usp-8',
    title: 'Crisis Income Redistribution',
    desc: 'During severe monsoons, heatwaves, or illness, cooperative emergency pools supplement worker baseline income.',
    icon: 'HeartHandshake',
    badge: 'Social Safety Net',
  },
  {
    id: 'usp-9',
    title: 'Multi-Person Team Booking',
    desc: 'Easily book verified multi-worker crews for large residences, office facilities, or community events.',
    icon: 'Users2',
    badge: 'Crew Dispatch',
  }
];

export const FAQS_DATA = [
  {
    category: 'Workers',
    question: 'How is Sahayak Seva different from commercial gig apps like Urban Company?',
    answer: 'Unlike corporate platforms that extract 30-40% in commissions and use opaque algorithms to de-prioritize workers, Sahayak Seva is owned by worker cooperatives. 80% of client payments go directly into the worker’s bank account, 5% funds health and accident insurance, and 10% builds cooperative assets. Workers vote on their own wage rates and have a peer jury to resolve disputes.',
  },
  {
    category: 'Workers',
    question: 'What is the Worker Algorithmic Appeal System?',
    answer: 'If an algorithm detects a delayed arrival or an upset client submits an unfair retaliatory review, your account is NEVER automatically suspended. You can file an appeal with evidence (GPS logs, photos). A panel of 15 fellow cooperative workers reviews the case and votes democratically within 48 hours.',
  },
  {
    category: 'Customers',
    question: 'Are Sahayak Seva workers background-checked and verified?',
    answer: 'Yes, 100%. Every worker undergoes government ID verification, criminal background check, and skill certification by national trade guilds (NSDC, IPA, state wireman licensing). Furthermore, each worker is vouched for by their local cooperative chapter.',
  },
  {
    category: 'Customers',
    question: 'What happens if I am not satisfied with the service provided?',
    answer: 'All our services include a Cooperative Satisfaction Guarantee. If any aspect falls short of the agreed checklist, a verified guild supervisor or senior team member will re-inspect and rectify the job within 48 hours at zero additional cost.',
  },
  {
    category: 'Businesses',
    question: 'Can businesses book multi-worker teams for office and facility maintenance?',
    answer: 'Yes! We provide enterprise billing, GST-compliant invoicing, and dedicated multi-member crews for facility management, office sanitization, electrical maintenance, and corporate events with zero agency markup.',
  }
];

export const BLOG_POSTS_DATA = [
  {
    id: 'blog-1',
    title: 'Why Digital Cooperatives Are the Future of the Indian Gig Economy',
    slug: 'future-of-indian-gig-cooperatives',
    category: 'Policy & Impact',
    date: 'Sep 05, 2026',
    author: 'Priya Patel (Federation Secretary)',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&q=80&w=800',
    excerpt: 'How moving from speculative venture-capital extraction to democratic worker ownership creates sustainable livelihoods, better customer experiences, and true social safety nets.',
  },
  {
    id: 'blog-2',
    title: 'Demystifying the 80/5/10/5 Wage Transparency Model',
    slug: 'wage-transparency-model-explained',
    category: 'Economics',
    date: 'Aug 28, 2026',
    author: 'Sunita Sharma (Electrician Guild)',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=800',
    excerpt: 'A deep-dive into where every single rupee goes when you book a home service on Sahayak Seva, and why commercial platform opacity hurts both customers and gig workers.',
  },
  {
    id: 'blog-3',
    title: 'Women in Trades: How Gender-First Safety Protocols Enable Livelihoods',
    slug: 'women-in-trades-safety-network',
    category: 'Empowerment',
    date: 'Aug 18, 2026',
    author: 'Ananya Deshmukh (Healthcare Lead)',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
    excerpt: 'Examining how verified household screening, emergency dispatch circles, and peer chaperoning make technical trades welcoming and secure for women professionals.',
  }
];

// ─── AGENCIES ────────────────────────────────────────────────────────────────
import { Agency, BatchBooking, Bundle, CustomService, CrisisEvent, DemandForecast, SafetyIncident, TeamJob, ComplianceRecord } from '@/types';

export const AGENCIES_DATA: Agency[] = [
  {
    id: 'agn-001',
    name: 'CleanPro Services Pvt. Ltd.',
    logoUrl: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&q=80&w=200',
    tagline: 'ISO-certified commercial cleaning & facility management',
    city: 'New Delhi',
    servicesOffered: ['Deep Cleaning', 'Office Sanitization', 'Post-Construction Cleaning'],
    rating: 4.7,
    totalReviews: 312,
    workersCount: 48,
    responseTime: '2 hours',
    qualityGuarantee: 'Free re-service within 48 hours',
    insuranceCoverage: '₹50 Lakh public liability',
    verified: true,
    status: 'approved',
    monthlyRevenue: 320000,
    satisfactionScore: 94,
    slaCompliancePercent: 97,
    createdAt: '2024-01-15',
  },
  {
    id: 'agn-002',
    name: 'TechFix Solutions',
    logoUrl: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&q=80&w=200',
    tagline: 'Expert electrical, plumbing & AC maintenance teams',
    city: 'Bengaluru',
    servicesOffered: ['Electrical Repairs', 'Plumbing', 'AC Service', 'Appliance Repair'],
    rating: 4.5,
    totalReviews: 189,
    workersCount: 32,
    responseTime: '4 hours',
    qualityGuarantee: 'Parts warranty up to 90 days',
    insuranceCoverage: '₹25 Lakh public liability',
    verified: true,
    status: 'approved',
    monthlyRevenue: 210000,
    satisfactionScore: 91,
    slaCompliancePercent: 93,
    createdAt: '2024-03-22',
  },
  {
    id: 'agn-003',
    name: 'GreenScape Maintenance',
    logoUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&q=80&w=200',
    tagline: 'Landscaping, pest control & outdoor facility care',
    city: 'Mumbai',
    servicesOffered: ['Pest Control', 'Gardening', 'Outdoor Cleaning'],
    rating: 4.3,
    totalReviews: 97,
    workersCount: 18,
    responseTime: '24 hours',
    qualityGuarantee: 'Monthly maintenance contracts',
    insuranceCoverage: '₹10 Lakh public liability',
    verified: false,
    status: 'pending',
    monthlyRevenue: 95000,
    satisfactionScore: 87,
    slaCompliancePercent: 88,
    createdAt: '2026-08-10',
  },
];

// ─── BATCH BOOKINGS ──────────────────────────────────────────────────────────
export const BATCH_BOOKINGS_DATA: BatchBooking[] = [
  {
    id: 'batch-001',
    createdBy: 'usr-cust-02',
    societyName: 'Riverside Residency RWA',
    totalHouseholds: 5,
    households: [
      { address: 'Flat 101, Riverside Residency', serviceType: 'Deep Cleaning', preferredTime: '9:00 AM', status: 'completed' },
      { address: 'Flat 203, Riverside Residency', serviceType: 'Deep Cleaning', preferredTime: '11:00 AM', status: 'completed' },
      { address: 'Flat 305, Riverside Residency', serviceType: 'Deep Cleaning', preferredTime: '1:00 PM', status: 'completed' },
      { address: 'Flat 412, Riverside Residency', serviceType: 'Deep Cleaning', preferredTime: '3:00 PM', status: 'pending' },
      { address: 'Flat 501, Riverside Residency', serviceType: 'Deep Cleaning', preferredTime: '5:00 PM', status: 'pending' },
    ],
    totalCost: 4400,
    individualCost: 5000,
    savingsPercent: 12,
    assignedWorkerId: 'wkr-001',
    scheduledDate: '2026-09-15',
    status: 'in-progress',
  },
];

// ─── BUNDLES ─────────────────────────────────────────────────────────────────
export const BUNDLES_DATA: Bundle[] = [
  {
    id: 'bundle-001',
    name: 'AC Service + Pest Control',
    services: ['AC Deep Clean & Gas Refill', 'Home Pest Control'],
    discountPercent: 15,
    totalPrice: 2125,
    originalPrice: 2500,
    popularityPercent: 87,
    description: '87% of customers who book AC service also book pest control within 2 weeks.',
  },
  {
    id: 'bundle-002',
    name: 'Deep Clean + Plumbing Check',
    services: ['Full Home Deep Cleaning', 'Plumbing Inspection & Minor Repairs'],
    discountPercent: 12,
    totalPrice: 2200,
    originalPrice: 2500,
    popularityPercent: 72,
    description: 'A clean home with working plumbing — the most popular combo in our network.',
  },
  {
    id: 'bundle-003',
    name: 'Electrical + Carpentry',
    services: ['Electrical Safety Audit', 'Furniture Repair & Carpentry'],
    discountPercent: 10,
    totalPrice: 1800,
    originalPrice: 2000,
    popularityPercent: 61,
    description: 'Perfect for home renovation or post-monsoon maintenance.',
  },
];

// ─── CUSTOM SERVICES ─────────────────────────────────────────────────────────
export const CUSTOM_SERVICES_DATA: CustomService[] = [
  {
    id: 'cs-001',
    customerId: 'usr-cust-02',
    customerName: 'Rahul Verma',
    rawDescription: 'I need someone to restore my grandfather\'s antique wooden dining set. It\'s from the 1950s, 6 chairs and a table, heavily scratched and the polish is gone.',
    aiSummary: {
      service_title: 'Antique Furniture Restoration',
      description: 'Restore a 1950s wooden dining set (6 chairs + 1 table) — stripping old polish, sanding, re-staining, and applying protective varnish.',
      required_skills: ['woodworking', 'furniture restoration', 'polishing', 'finishing'],
      estimated_duration: '10-14 hours',
      team_size: '2 people',
      complexity_level: 'advanced',
    },
    budgetMin: 3000,
    budgetMax: 8000,
    timeline: '3-5 days',
    location: 'Golf Links, New Delhi',
    status: 'bidding',
    bids: [
      {
        id: 'bid-001',
        workerId: 'wkr-003',
        workerName: 'Ravi Kumar',
        workerPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
        workerRating: 4.9,
        bidAmount: 5500,
        timeline: '4 days',
        description: 'Experienced in antique restoration. Will use traditional lacquer finish for authenticity.',
        createdAt: '2026-09-11',
      },
      {
        id: 'bid-002',
        workerId: 'wkr-004',
        workerName: 'Deepak Mehra',
        workerPhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
        workerRating: 4.6,
        bidAmount: 4200,
        timeline: '3 days',
        description: 'Heritage carpentry specialist. Will provide 1-year guarantee on finish.',
        createdAt: '2026-09-11',
      },
    ],
    createdAt: '2026-09-10',
  },
];

// ─── CRISIS EVENTS ───────────────────────────────────────────────────────────
export const CRISIS_EVENTS_DATA: CrisisEvent[] = [
  {
    id: 'crisis-001',
    name: 'Monsoon Season 2026',
    trigger: 'Demand dropped 43% below baseline; IMD heavy rainfall advisory active',
    severity: 'moderate',
    status: 'active',
    demandDropPercent: 43,
    startDate: '2026-07-01',
    workersProtected: 1240,
    allocationSplit: { rating: 60, vulnerability: 40 },
  },
  {
    id: 'crisis-002',
    name: 'Delhi Air Quality Crisis (Nov 2025)',
    trigger: 'AQI > 400; outdoor work suspended by CAQM order',
    severity: 'high',
    status: 'resolved',
    demandDropPercent: 67,
    startDate: '2025-11-01',
    endDate: '2025-11-21',
    workersProtected: 890,
    allocationSplit: { rating: 40, vulnerability: 60 },
  },
];

// ─── DEMAND FORECAST ─────────────────────────────────────────────────────────
export const DEMAND_FORECAST_DATA: DemandForecast[] = [
  { day: 'Mon', cleaning: 42, electrical: 18, plumbing: 12, pestControl: 8, carpentry: 6, total: 86 },
  { day: 'Tue', cleaning: 38, electrical: 22, plumbing: 15, pestControl: 10, carpentry: 5, total: 90 },
  { day: 'Wed', cleaning: 45, electrical: 20, plumbing: 18, pestControl: 12, carpentry: 8, total: 103 },
  { day: 'Thu', cleaning: 50, electrical: 25, plumbing: 14, pestControl: 9, carpentry: 7, total: 105 },
  { day: 'Fri', cleaning: 60, electrical: 28, plumbing: 20, pestControl: 15, carpentry: 10, total: 133 },
  { day: 'Sat', cleaning: 80, electrical: 35, plumbing: 25, pestControl: 20, carpentry: 15, total: 175 },
  { day: 'Sun', cleaning: 75, electrical: 30, plumbing: 22, pestControl: 18, carpentry: 12, total: 157 },
];

// ─── SAFETY INCIDENTS ────────────────────────────────────────────────────────
export const SAFETY_INCIDENTS_DATA: SafetyIncident[] = [
  {
    id: 'inc-001',
    workerId: 'wkr-001',
    workerName: 'Sunita Sharma',
    customerId: 'cust-099',
    customerName: 'Arjun Malhotra',
    incidentType: 'harassment',
    severity: 'yellow',
    description: 'Customer made inappropriate comments about worker\'s appearance during service visit.',
    status: 'under_review',
    reportedAt: '2026-09-10T14:30:00Z',
    actionTaken: 'Customer warned via email. Safety review initiated.',
  },
  {
    id: 'inc-002',
    workerId: 'wkr-007',
    workerName: 'Meena Devi',
    customerId: 'cust-202',
    customerName: 'Rajesh Gupta',
    incidentType: 'payment_dispute',
    severity: 'yellow',
    description: 'Customer refused to pay full agreed amount after service completion.',
    status: 'resolved',
    reportedAt: '2026-09-05T10:15:00Z',
    resolvedAt: '2026-09-06T16:00:00Z',
    actionTaken: 'Mediation completed. Customer paid remaining amount. First warning issued.',
  },
];

// ─── TEAM JOBS ───────────────────────────────────────────────────────────────
export const TEAM_JOBS_DATA: TeamJob[] = [
  {
    id: 'team-001',
    bookingId: 'bk-team-001',
    serviceTitle: 'Office Deep Cleaning — BluePeak HQ',
    customerName: 'Amit Sen (BluePeak Facilities)',
    location: 'Sector 18, Noida',
    scheduledDate: '2026-09-18',
    scheduledTime: '8:00 AM',
    teamSize: 5,
    totalPay: 8000,
    perPersonPay: 1600,
    teamLeadId: 'wkr-001',
    members: [
      { id: 'wkr-001', name: 'Sunita Sharma', photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=100', role: 'lead' },
      { id: 'wkr-008', name: 'Preethi Nair', photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100', role: 'member' },
      { id: 'wkr-009', name: 'Kavya Reddy', photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=100', role: 'member' },
      { id: 'wkr-010', name: 'Rekha Singh', photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=100', role: 'member' },
      { id: 'wkr-011', name: 'Anita Kumari', photo: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80&w=100', role: 'member' },
    ],
    status: 'pending',
    stops: [
      { address: 'Ground Floor Reception', order: 1, status: 'pending' },
      { address: '2nd Floor Open Office', order: 2, status: 'pending' },
      { address: 'Server Room (Dust-free)', order: 3, status: 'pending' },
      { address: 'Executive Cabins (5)', order: 4, status: 'pending' },
      { address: 'Cafeteria & Restrooms', order: 5, status: 'pending' },
    ],
  },
];

// ─── COMPLIANCE ──────────────────────────────────────────────────────────────
export const COMPLIANCE_DATA: ComplianceRecord[] = [
  { workerId: 'wkr-001', workerName: 'Sunita Sharma', verificationStatus: 'verified', insuranceStatus: 'enrolled', backgroundCheck: 'clear', certExpiry: '2027-03-15', daysUntilExpiry: 184 },
  { workerId: 'wkr-002', workerName: 'Vikram Singh', verificationStatus: 'verified', insuranceStatus: 'enrolled', backgroundCheck: 'clear', certExpiry: '2026-12-01', daysUntilExpiry: 80 },
  { workerId: 'wkr-003', workerName: 'Ravi Kumar', verificationStatus: 'pending', insuranceStatus: 'pending', backgroundCheck: 'pending', certExpiry: '2026-10-10', daysUntilExpiry: 28 },
  { workerId: 'wkr-004', workerName: 'Deepak Mehra', verificationStatus: 'verified', insuranceStatus: 'enrolled', backgroundCheck: 'clear', certExpiry: '2027-06-20', daysUntilExpiry: 281 },
  { workerId: 'wkr-005', workerName: 'Ananya Iyer', verificationStatus: 'verified', insuranceStatus: 'lapsed', backgroundCheck: 'clear', certExpiry: '2026-09-20', daysUntilExpiry: 8 },
];

// ─── HERITAGE SKILLS CATALOG ─────────────────────────────────────────────────
export const HERITAGE_SKILLS_CATALOG = [
  { id: 'hs-1', name: 'Mughal Tilework (Zillij)', premium: 30, description: 'Geometric Islamic-inspired tile mosaic artistry from Mughal-era architecture.' },
  { id: 'hs-2', name: 'Heritage Carpentry (Shisham & Teak)', premium: 30, description: 'Traditional Indian joinery using Shisham rosewood and Burma teak without metal fasteners.' },
  { id: 'hs-3', name: 'Lime Plaster (Chunam)', premium: 25, description: 'Pre-industrial polished lime finish for heritage building restoration.' },
  { id: 'hs-4', name: 'Bidriware Metalwork', premium: 35, description: 'Intricate silver-inlaid zinc alloy craft from Bidar, Karnataka.' },
  { id: 'hs-5', name: 'Warli Art Murals', premium: 20, description: 'Traditional tribal wall-painting from Maharashtra, UNESCO heritage.' },
  { id: 'hs-6', name: 'Jaali Stone Lattice Carving', premium: 35, description: 'Ornamental perforated stone screens as seen in Mughal palaces and havelis.' },
];

// ─── ADMIN REPORTS ───────────────────────────────────────────────────────────
export const ADMIN_REPORTS_DATA = {
  monthlyRevenue: [
    { month: 'Apr', gmv: 3200000, workerNet: 2560000 },
    { month: 'May', gmv: 3800000, workerNet: 3040000 },
    { month: 'Jun', gmv: 4100000, workerNet: 3280000 },
    { month: 'Jul', gmv: 3600000, workerNet: 2880000 },
    { month: 'Aug', gmv: 4400000, workerNet: 3520000 },
    { month: 'Sep', gmv: 5000000, workerNet: 4000000 },
  ],
  serviceBreakdown: [
    { name: 'Cleaning', value: 38 },
    { name: 'Electrical', value: 22 },
    { name: 'Plumbing', value: 18 },
    { name: 'Pest Control', value: 12 },
    { name: 'Carpentry', value: 10 },
  ],
  keyMetrics: {
    totalGMV: 50000000,
    activeWorkers: 2500,
    customerSatisfaction: 94,
    utilizationRate: 78,
    pendingVerifications: 3,
    pendingAgencies: 2,
    pendingAppeals: 5,
    openEscalations: 1,
  },
};
